
spring:
  datasource:
    url: jdbc:h2:mem:restaurant
  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true


auth:
  token:
    key: asdasgjeiowjoviojjrwoi
    expiration: 3600
